version: '3.9'
services:
  database:
    image: mysql:latest
    container_name: api-database
    environment:
      MYSQL_ROOT_PASSWORD: thisisadmin
      MYSQL_DATABASE: nestjs  
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORTS: "3307"
    restart: always
    ports:
      - 8081:80
    depends_on:
      - database
  nestjs:
    container_name: nestjs
    build:
      dockerfile: docker/Dockerfile.Monolith
    ports:
      - "4000:4000"
    env_file:
      - .env.prod

    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    

volumes:
  dbdata: